package com.galhelper.dialogue.mapper;

import com.galhelper.dialogue.model.entity.AiConversationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface AiConversationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_conversation_info
     *
     * @mbg.generated Sun Jan 11 10:24:51 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_conversation_info
     *
     * @mbg.generated Sun Jan 11 10:24:51 CST 2026
     */
    int insert(AiConversationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_conversation_info
     *
     * @mbg.generated Sun Jan 11 10:24:51 CST 2026
     */
    AiConversationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_conversation_info
     *
     * @mbg.generated Sun Jan 11 10:24:51 CST 2026
     */
    List<AiConversationInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_conversation_info
     *
     * @mbg.generated Sun Jan 11 10:24:51 CST 2026
     */
    int updateByPrimaryKey(AiConversationInfo record);

    /**
     * 更新用户会话的意图信息
     * @param id 会话id
     * @param userIntent 意图
     * @param updateTime 更新时间
     */
    void updateIntentById(@Param("id") Long id, @Param("userIntent") Integer userIntent,
                          @Param("updateTime") Date updateTime);

    /**
     * 根据主键更新会话信息，只更新非空的字段
     * @param updateRecord 更新的会话信息
     * @return
     */
    int updateByPrimaryKeySelective(AiConversationInfo updateRecord);
}