package com.galhelper.dialogue.mapper;

import com.galhelper.dialogue.model.entity.AiMessageInfo;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AiMessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message_info
     *
     * @mbg.generated Sun Jan 11 10:31:57 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message_info
     *
     * @mbg.generated Sun Jan 11 10:31:57 CST 2026
     */
    int insert(AiMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message_info
     *
     * @mbg.generated Sun Jan 11 10:31:57 CST 2026
     */
    AiMessageInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message_info
     *
     * @mbg.generated Sun Jan 11 10:31:57 CST 2026
     */
    List<AiMessageInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message_info
     *
     * @mbg.generated Sun Jan 11 10:31:57 CST 2026
     */
    int updateByPrimaryKey(AiMessageInfo record);
}